name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: rebar3 steamroll --check
    - name: Compile
      run: rebar3 compile
    - name: Run enuit tests
      run: rebar3 eunit
    - name: Prepare scripts
      run: chmod +x test/*.sh
    - name: Generate CT tests
      env:
        GENERATE_COMPACTED: true
        GENERATE_CT: true
        GENERATE_EUNIT: false
        GENERATE_PERFORMANCE: true
        GENERATE_RELIABILITY: true
        HEAP_SIZE: +hms 33554432
        LOGGING: false
        MAX_BASIC: 200
      run: ./test/gen_tests.sh
    - name: Run generated CT
      run: rebar3 ct
    - name: Run cover
      run: rebar3 cover
    - name: Run geas
      run: rebar3 as test geas
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run coveralls
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: rebar3 as test coveralls send

